kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
  namespace: expense 
  labels:
    project: expense
    component: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]