kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
  namespace: expense 
  labels:
    project: expense
    component: frontend
spec:
  containers:
  - name: nginx
      image: nginx
    livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
  - name: almalinux
      image: almalinux:9
    