kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
  namespace: expense 
  labels:
    project: expense
    component: frontend
spec:
  containers:
      livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
- name: nginx
   image: nginx
- name: almalinux
  image: almalinux:9
    