kind: pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: devsecops
    - name: tariner
      value: sai
    - name: duraion
      value: 120hrs