kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft liit
    requests:
      memory: "68Mi"
      cpu: "250m"
      # hard limit
    limits:
      requests: "128Mi"
      cpu: "500m"
