kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft liit
    requests:
      memory: "68Mi"
      cpu: "100m"
      # hard
    limits:
      requests: ""
      cpu:
