apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: expense
  # lables of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
    replicas: 2
    selector:
      matchLabels:
        app: nginx  
        tier: frontend
        purpose: deployment
    template:
      metadata:
        labels:
          app: nginx
          tier: frontend
          purpose: deployment
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80